# Generated by Django 5.2.3 on 2025-07-31 13:23

import Gestion.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdreDeMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('nom_prenom', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('motif', models.CharField(max_length=50)),
                ('moyen_deplacement', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=50)),
                ('matricule_2', models.CharField(blank=True, max_length=50, null=True)),
                ('date_depart', models.DateField()),
                ('date_retour', models.DateField(blank=True, null=True)),
                ('accompagne_par', models.CharField(blank=True, max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='System', max_length=50)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BonDeCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('date_commande', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=Gestion.models.bon_commande_pdf_path)),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bon_commandes', to=settings.AUTH_USER_MODEL)),
                ('pdf_generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_bc_pdfs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BonDeLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bl_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('origin_address', models.TextField()),
                ('destination_address', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('payment_method', models.CharField(choices=[('virement', 'Virement'), ('espece', 'Espèce'), ('cheque', 'Chèque')], max_length=20)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('nom_fournisseur', models.CharField(blank=True, max_length=200, null=True)),
                ('banque', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_cheque', models.CharField(blank=True, max_length=100, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=Gestion.models.bon_livraison_pdf_path)),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bon_livraisons', to=settings.AUTH_USER_MODEL)),
                ('pdf_generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_pdfs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bon_de_livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_charges', to='Gestion.bondelivraison')),
            ],
        ),
        migrations.CreateModel(
            name='Dette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditor_name', models.CharField(help_text='Name of the person/entity you took money from', max_length=200)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='CaisseOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('encaissement', 'Encaissement'), ('decaissement', 'Décaissement')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(blank=True)),
                ('preuve_file', models.FileField(blank=True, null=True, upload_to='caisse_preuves/')),
                ('mode_paiement', models.CharField(blank=True, choices=[('virement', 'Virement'), ('espece', 'Espèce'), ('cheque', 'Chèque')], max_length=20, null=True)),
                ('nom_fournisseur', models.CharField(blank=True, max_length=200, null=True)),
                ('banque', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_cheque', models.CharField(blank=True, max_length=100, null=True)),
                ('income_source', models.CharField(blank=True, choices=[('personnelle', 'Personnelle'), ('collaborator', 'Collaborateur'), ('dette', 'Dette'), ('autre', 'Autre')], max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('observation', models.TextField(blank=True, help_text="Required when income_source is 'autre'", null=True)),
                ('by_collaborator', models.BooleanField(default=False, help_text='Indicates if the operation is by a collaborator')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField(help_text='User input date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion.dette')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DettePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('preuve_file', models.FileField(blank=True, null=True, upload_to='dette_payments/')),
                ('mode_paiement', models.CharField(choices=[('virement', 'Virement'), ('espece', 'Espèce'), ('cheque', 'Chèque')], max_length=20)),
                ('nom_fournisseur', models.CharField(blank=True, max_length=200, null=True)),
                ('banque', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_cheque', models.CharField(blank=True, max_length=100, null=True)),
                ('caisse_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion.caisseoperation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Gestion.dette')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='BonDeLivraisonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bon_de_livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Gestion.bondelivraison')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.product')),
            ],
        ),
        migrations.CreateModel(
            name='BonDeCommandeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('montant_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bon_de_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Gestion.bondecommande')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.product')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('estimated_budget', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('ods_file', models.FileField(blank=True, null=True, upload_to='ods_files/')),
                ('operation', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_operation', models.CharField(blank=True, max_length=100, null=True)),
                ('date_debut', models.DateField()),
                ('period_months', models.PositiveIntegerField(help_text='Duration in months')),
                ('collaborator_name', models.CharField(blank=True, max_length=200, null=True)),
                ('total_depenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_benefices', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dette',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dettes', to='Gestion.project'),
        ),
        migrations.AddField(
            model_name='caisseoperation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion.project'),
        ),
        migrations.CreateModel(
            name='CaisseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=10, unique=True)),
                ('action', models.CharField(choices=[('encaissement', 'Encaissement'), ('decaissement', 'Décaissement'), ('balance_adjustment', 'Balance Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(help_text='User input date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion.caisseoperation')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BonLivraisonHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bl_number', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('pdf_generated', 'PDF Generated'), ('pdf_downloaded', 'PDF Downloaded'), ('deleted', 'Deleted')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bon_de_livraison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion.bondelivraison')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bl_history', to='Gestion.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bondelivraison',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bon_livraisons', to='Gestion.project'),
        ),
        migrations.CreateModel(
            name='Revenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenu_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=Gestion.models.revenu_pdf_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_revenus', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenus', to='Gestion.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
