# Generated by Django 5.2.3 on 2025-06-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdreDeMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('nom_prenom', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('motif', models.CharField(max_length=50)),
                ('moyen_deplacement', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=50)),
                ('date_depart', models.DateField()),
                ('date_retour', models.CharField(default='FIN DE MISSION', max_length=50)),
                ('accompagne_par', models.CharField(blank=True, max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='System', max_length=50)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
