# Generated by Django 5.2.3 on 2025-08-01 13:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_accreance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='revenu',
            name='revenu_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
