# Generated by Django 5.2.3 on 2025-08-02 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_project_total_accreance_alter_revenu_revenu_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caisseoperation',
            name='bank_name',
        ),
    ]
