# Generated by Django 5.2.3 on 2025-07-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_ordredemission_matricule_2_project_caisse_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcaisseoperation',
            name='preuve_type',
            field=models.CharField(blank=True, choices=[('bank', 'Bank'), ('cheque', 'Chèque'), ('espece', 'Espèce'), ('virement', 'Virement')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='projectcaisseoperation',
            name='operation_type',
            field=models.CharField(choices=[('encaissement', 'Encaissement'), ('decaissement', 'Décaissement'), ('expense', 'Expense'), ('adjustment', 'Adjustment')], max_length=15),
        ),
    ]
