# Generated by Django 5.2.3 on 2025-09-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_remove_caisseoperation_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondecommande',
            name='doit',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
