# Generated by Django 5.2.3 on 2025-07-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0004_projectcaisseoperation_preuve_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordredemission',
            name='date_retour',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectcaisseoperation',
            name='operation_type',
            field=models.CharField(choices=[('encaissement', 'Encaissement'), ('decaissement', 'Décaissement'), ('remboursement', 'Remboursement'), ('ُexpense', 'Expense')], max_length=15),
        ),
    ]
