# Generated by Django 5.2.3 on 2025-07-08 08:31

import Gestion.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0005_alter_ordredemission_date_retour_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonDeCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('date_commande', models.DateField(auto_now_add=True)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=Gestion.models.bon_commande_pdf_path)),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bon_commandes', to=settings.AUTH_USER_MODEL)),
                ('pdf_generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_bc_pdfs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BonDeCommandeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('montant_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bon_de_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Gestion.bondecommande')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.product')),
            ],
        ),
    ]
