# Generated by Django 5.2.3 on 2025-07-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0006_bondecommande_bondecommandeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcaisseoperation',
            name='by_collaborator',
            field=models.BooleanField(default=False, help_text='Indicates if the operation was done by a project collaborator'),
        ),
    ]
