# Generated by Django 5.2.3 on 2025-06-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='Default_pfp.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
